services:
  backend:
    build:
      context: ./backend
    container_name: agentcare-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app  # Enables hot-reloading during development
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    container_name: agentcare-frontend
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:                     # Add this section
      - PYTHONUNBUFFERED=1           # Forces print() to output immediately
    depends_on:
      - backend
    volumes:
      - ./frontend:/app # Enables hot-reloading during development
    # command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    command: python -m streamlit run app.py --server.port=8501 --server.address=0.0.0.0