from fastapi import FastAPI
from pydantic import BaseModel
from graph import app_graph
from langchain_core.messages import HumanMessage

app = FastAPI(title="Agentic Healthcare API")

# Define the expected input from the frontend
class ChatRequest(BaseModel):
    message: str
    user_id: str = 'default_user'

@app.get("/")
def health_check():
    return {"status": "Backend is running flawlessly!"}


@app.post("/chat")
def chat_endpoint(request: ChatRequest):
    # 1. Format the input for the graph
    initial_state = {
        "messages": [HumanMessage(content=request.message)],
        "user_context": {"id": request.user_id},
        "task_status": "pending",
        "workflow_data": {}
    }

    # 2. Run the graph (this executes the router_node)
    final_state = app_graph.invoke(initial_state)

    # 3. Extract the last message generated by the AI
    ai_response = final_state["messages"][-1].content

    return {"response": ai_response, "task_status": final_state["task_status"]}